import test from 'node:test';
import assert from 'node:assert/strict';
import {recipeProgress,recipeMarkers,recipeColor} from '../web/recipe-progress.js';
const steps=[{trigger:'time',at:0,control:'power',value:5},{trigger:'time',at:0,control:'fan',value:2},{trigger:'ibts',at:170,min_time:90,control:'power',value:4},{trigger:'ibts',at:185,min_time:90,control:'fan',value:3}];
const runner={state:'running',completed:[0,1],skipped:[],initializing:false,applying_index:null,last_completed_index:1};
test('prepared recipe groups starting settings and never invents a current step',()=>{const p=recipeProgress(steps,null,null);assert.equal(p.nodes.length,3);assert.equal(p.nodes[0].next,true);assert.equal(p.nodes.some(n=>n.current),false);assert.deepEqual(p.nodes[0].indices,[0,1]);});
test('last confirmed step stays current until another is applying',()=>{let p=recipeProgress(steps,runner,'roasting');assert.equal(p.nodes[0].caption,'Current');assert.equal(p.nodes[1].next,true);p=recipeProgress(steps,{...runner,applying_index:2},'roasting');assert.equal(p.nodes[1].caption,'Applying');assert.equal(p.nodes[1].state,'upcoming');assert.equal(p.nodes[0].state,'done');});
test('completed steps can arrive out of order without falsely completing earlier ones',()=>{const p=recipeProgress(steps,{...runner,completed:[0,1,3],last_completed_index:3},'roasting');assert.equal(p.nodes[2].current,true);assert.equal(p.nodes[1].state,'upcoming');assert.equal(p.nodes[1].next,true);});
test('paused and skipped actions do not claim current machine settings',()=>{const p=recipeProgress(steps,{...runner,state:'paused',skipped:[2]},'roasting');assert.equal(p.summary,'Recipe paused');assert.equal(p.nodes[0].caption,'Last applied');assert.equal(p.nodes[1].state,'skipped');});
test('cooling has no active recipe step and complete does not mean the roast ended',()=>{let p=recipeProgress(steps,{...runner,state:'stopped'},'cooling');assert.equal(p.nodes.some(n=>n.current),false);p=recipeProgress(steps,{...runner,state:'complete',completed:[0,1,2,3],last_completed_index:3},'roasting');assert.equal(p.nodes[2].caption,'Current');assert.match(p.summary,/choose when to cool/);});

test('every segment carries complete settings forward',()=>{const p=recipeProgress(steps,null,null);assert.deepEqual(p.nodes.map(n=>n.settings),[{power:5,fan:2,drum:9},{power:4,fan:2,drum:9},{power:4,fan:3,drum:9}]);assert.equal(new Set(p.nodes.map(n=>n.color)).size,3);});
test('step dots use recorded starts, ignore malformed events and never duplicate',()=>{const value=JSON.stringify({step:2,elapsed:95,ibts:171,settings:{power:4,fan:4,drum:9}});const events=[{kind:'recipe_step',value},{kind:'recipe_step',value},{kind:'recipe_step',value:'oops'},{kind:'control',value}];assert.equal(recipeMarkers(events).length,1);assert.equal(recipeColor(1),recipeProgress(steps,runner,'roasting',events).nodes[1].color);assert.equal(recipeProgress(steps,runner,'roasting',events).nodes[1].settings.fan,4);assert.deepEqual(recipeMarkers([]),[]);});
